---
project: aws-hello
default-region: us-east-1
code-bucket: grist-apigateway-001
apps:
  - gordon.contrib.lambdas
  - helloworld

apigateway:
  helloapi:
    description: My very first API from cicd
    resources:
      /:
        methods: GET
        integration:
          lambda: helloworld.hellopy